[project]
name = "firstproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "geopandas>=1.0.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
